### ISSUE TITLE
Unikalne odwiedziny: 

### ISSUE THREAD

**Issue by szogun1910** [stalkerlifehack/qBot-your-TeamSpeak-automation#1]
Hej, jesteś w stanie zrobić coś na zasadzie aby codziennie resetowało ten licznik, coś na zasadzie aby pokazywało ile osób codziennie się łączyło z serwerem np gdy dana osoba połączy się dwa razy jego drugie połączenie już nie zostanie brane pod uwagę w ciągu np 24h

**Comment by stalkerlifehack** [comment]
Hej, postaram się dodać do końca tygodnia ;)

**Comment by szogun1910** [comment]
@stalkerlifehack hej i jak tam uda się coś z tym wymodzić ?
